apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default  # Namespace added here
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer
  ports:
    - port: 80         # The port exposed by the service
      targetPort: 80    # Port on the container that the service will forward traffic to
  selector:
    app: deploy-nginx  # Ensure this matches the label of your Deployment
